package com.example.consumerservice.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

@Entity
@Table(name = "adjustment_ssy")
@Data
public class AdjustmentSSY {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  private Long idJob;
  private String edpCode;
  private LocalDateTime applicationDateStart;
  private LocalDateTime applicationDateEnd;
  private LocalDateTime periodStart;
  private LocalDateTime periodEnd;
  private LocalDateTime updateDate;
  private LocalDateTime receivedDate;

  /**
   * Converts a Kafka model object to a JPA entity.
   *
   * @param kafkaModel The Kafka model object.
   * @return A new AdjustmentSSY entity.
   */
  public static AdjustmentSSY fromKafkaModel(AdjustmentSSYKafka kafkaModel) {
    return new AdjustmentSSY(
            null, // ID is auto-generated by the database
            kafkaModel.getIdJob(),
            kafkaModel.getEdpCode(),
            kafkaModel.getApplicationDateStart(),
            kafkaModel.getApplicationDateEnd(),
            kafkaModel.getPeriodStart(),
            kafkaModel.getPeriodEnd(),
            kafkaModel.getUpdateDate(),
            kafkaModel.getReceivedDate()
    );
  }
  /*public static AdjustmentSSY fromKafkaModel(AdjustmentSSYKafka kafkaModel) {
    return new AdjustmentSSY(
            null, // ID is auto-generated by the database
            kafkaModel.getIdJob(),
            kafkaModel.getEdpCode().toString(), // Convert Avro Utf8 to String
            toLocalDateTime(kafkaModel.getApplicationDateStart()),
            toLocalDateTime(kafkaModel.getApplicationDateEnd()),
            toLocalDateTime(kafkaModel.getPeriodStart()),
            toLocalDateTime(kafkaModel.getPeriodEnd()),
            toLocalDateTime(kafkaModel.getUpdateDate()),
            toLocalDateTime(kafkaModel.getReceivedDate())
    );
  }*/


  // Helper method to convert to LocalDateTime based on type (Long or CharSequence)
/*
  private static LocalDateTime toLocalDateTime(Object timestamp) {
    if (timestamp instanceof Long) {
      // If it's a Long (epochMillis), convert it to LocalDateTime
      return LocalDateTime.ofInstant(Instant.ofEpochMilli((Long) timestamp), ZoneId.systemDefault());
    } else if (timestamp instanceof CharSequence) {
      // If it's a CharSequence (String or Utf8), parse it as ISO-8601 format
      return LocalDateTime.parse(timestamp.toString(), DateTimeFormatter.ISO_DATE_TIME);
    }
    return null; // Return null if the timestamp is of an unsupported type
  }
*/

  public AdjustmentSSY() {
  }

  public Long getId() {
    return id;
  }

  public Long getIdJob() {
    return idJob;
  }

  public String getEdpCode() {
    return edpCode;
  }

  public LocalDateTime getApplicationDateStart() {
    return applicationDateStart;
  }

  public LocalDateTime getApplicationDateEnd() {
    return applicationDateEnd;
  }

  public LocalDateTime getPeriodStart() {
    return periodStart;
  }

  public LocalDateTime getPeriodEnd() {
    return periodEnd;
  }

  public LocalDateTime getUpdateDate() {
    return updateDate;
  }

  public LocalDateTime getReceivedDate() {
    return receivedDate;
  }

  public AdjustmentSSY(Long id, Long idJob, String edpCode, LocalDateTime applicationDateStart, LocalDateTime applicationDateEnd, LocalDateTime periodStart, LocalDateTime periodEnd, LocalDateTime updateDate, LocalDateTime receivedDate) {
    this.id = id;
    this.idJob = idJob;
    this.edpCode = edpCode;
    this.applicationDateStart = applicationDateStart;
    this.applicationDateEnd = applicationDateEnd;
    this.periodStart = periodStart;
    this.periodEnd = periodEnd;
    this.updateDate = updateDate;
    this.receivedDate = receivedDate;
  }
}
